// Mech icon helper: inline <img> portraits rendered from the real models
// (public/thumbs/<id>.png, generated by tools/thumbs.mjs). Falls back to
// the roster emoji if a thumbnail is missing so nothing ever renders blank.
export function mechIcon(def, size = 22) {
  const r = Math.round(size * 0.22);
  const dip = Math.round(size * 0.22);
  return `<img class="mech-ico" src="thumbs/${def.id}.png" alt="${def.icon}" ` +
    `style="width:${size}px;height:${size}px;border-radius:${r}px;object-fit:cover;` +
    `vertical-align:-${dip}px;margin-right:${Math.max(3, Math.round(size * 0.14))}px;` +
    `background:#0a121c;box-shadow:0 0 0 1px rgba(120,200,255,0.25)" ` +
    `onerror="this.outerHTML='${def.icon}'">`;
}
