// The 12 fighters: proportions, palettes, stats, personalities, move sets.
// All combat numbers live here so balance is tuned in one place.

export const ROSTER = [
  {
    id: 'titanus', name: 'TITANUS', title: 'The Iron Avalanche', icon: '👊', seed: 11,
    blurb: 'A decommissioned siege engine that refused to power down. Slow as a glacier, hits like the end of the world. Speaks rarely — mostly in earthquakes.',
    quotes: { win: '"Demolition complete. Anything else need... flattening?"', intro: '"I am the wall. I am the wrecking ball."' },
    colors: { primary: 0xc98a1b, accent: 0x4a4d55, glow: 0xffb43c, stripes: true },
    body: { scale: 1.28, torsoW: 1.25, torsoH: 1.05, headSize: 0.9, armLen: 1.15, legLen: 1.0, hipW: 1.15, bulk: 1.1 },
    stats: { hp: 1250, speed: 7.2, jump: 12, weight: 1.0, armor: 0.22 },
    ui: { power: 10, speed: 3, defense: 9 },
    moves: {
      light: { dmg: [46, 50, 68], knock: [6, 7, 16], range: 3.4 },
      heavy: { dmg: 105, knock: 26, range: 3.8, launch: 9 },
      ranged: { name: 'Rocket Fist', type: 'rocket', dmg: 70, speed: 32, cooldown: 1.6, splash: 4.5 },
      special: { id: 'groundPound', name: 'Seismic Slam', cooldown: 7, dmg: 85, radius: 9, knock: 24 },
      ult: { id: 'meteorBreaker', name: 'METEOR BREAKER', dmg: 220, radius: 13, knock: 34 },
    },
  },
  {
    id: 'vulcan', name: 'VULCAN', title: 'The Lead Storm', icon: '🔫', seed: 22,
    blurb: 'Ex-military fire-support platform with a laugh setting stuck on maniacal. Believes every problem is just insufficient ammunition.',
    quotes: { win: '"HAHAHA! Reload and repeat! WHO\'S NEXT?!"', intro: '"Say hello to my six little friends!"' },
    colors: { primary: 0x5d6b3c, accent: 0x8a6d3b, glow: 0xff5040, stripes: false },
    body: { scale: 1.1, torsoW: 1.1, torsoH: 1.0, headSize: 0.85, armLen: 1.0, legLen: 1.0, hipW: 1.0, bulk: 1.0 },
    stats: { hp: 950, speed: 9.5, jump: 13, weight: 0.62, armor: 0.1 },
    ui: { power: 7, speed: 5, defense: 5 },
    moves: {
      light: { dmg: [30, 32, 44], knock: [4, 5, 11], range: 2.9 },
      heavy: { dmg: 78, knock: 18, range: 3.2, launch: 7 },
      ranged: { name: 'Gatling Burst', type: 'gatling', dmg: 9, speed: 90, cooldown: 0.085, spread: 0.05 },
      special: { id: 'missileVolley', name: 'Micro-Missile Volley', cooldown: 6.5, dmg: 26, count: 6 },
      ult: { id: 'bulletHurricane', name: 'BULLET HURRICANE', dmg: 12, duration: 3.2 },
    },
  },
  {
    id: 'aegis', name: 'AEGIS', title: 'The Bastion of Dawn', icon: '🛡️', seed: 33,
    blurb: 'A knight-errant forged from cathedral steel. Sworn to protect the innocent, the outnumbered, and anyone standing behind that enormous shield.',
    quotes: { win: '"Honor is the finest armor. Yield with grace, friend."', intro: '"By dawn\'s light — I shall not falter!"' },
    colors: { primary: 0xc6ccd4, accent: 0xc9a227, glow: 0x49b7ff, stripes: false },
    body: { scale: 1.15, torsoW: 1.08, torsoH: 1.05, headSize: 0.9, armLen: 1.05, legLen: 1.05, hipW: 1.0, bulk: 1.0 },
    stats: { hp: 1100, speed: 8.4, jump: 12.5, weight: 0.78, armor: 0.16 },
    ui: { power: 6, speed: 4, defense: 10 },
    moves: {
      light: { dmg: [34, 36, 50], knock: [5, 5, 12], range: 3.6 },
      heavy: { dmg: 88, knock: 20, range: 4.2, launch: 8 },
      ranged: { name: 'Lance Wave', type: 'wave', dmg: 44, speed: 38, cooldown: 1.1 },
      special: { id: 'shieldBash', name: 'Bulwark Bash', cooldown: 6, dmg: 60, knock: 22, guard: 2.2 },
      ult: { id: 'judgment', name: 'JUDGMENT RAY', dmg: 200, radius: 8 },
    },
  },
  {
    id: 'viper', name: 'VIPER', title: 'The Whispering Fang', icon: '🗡️', seed: 44,
    blurb: 'A prototype infiltration unit that developed a taste for theatrics. Strikes from angles geometry teachers refuse to acknowledge.',
    quotes: { win: '"Ssso predictable. You never even sssaw me."', intro: '"Shall we dance? You won\'t hear the music."' },
    colors: { primary: 0x3d2a54, accent: 0x1c1424, glow: 0x6cff5c, stripes: false },
    body: { scale: 1.0, torsoW: 0.85, torsoH: 0.95, headSize: 0.85, armLen: 1.05, legLen: 1.12, hipW: 0.85, bulk: 0.85 },
    restPose: { thighL: [-31, 0, 0], thighR: [-31, 0, 0], kneeL: [57, 0, 0], kneeR: [57, 0, 0], ankleL: [-26, 0, 0], ankleR: [-26, 0, 0] },
    stats: { hp: 780, speed: 13.5, jump: 15.5, weight: 0.3, armor: 0 },
    ui: { power: 6, speed: 10, defense: 2 },
    moves: {
      light: { dmg: [26, 28, 40], knock: [3, 4, 9], range: 3.2 },
      heavy: { dmg: 70, knock: 15, range: 3.6, launch: 8 },
      ranged: { name: 'Venom Dart', type: 'dart', dmg: 30, speed: 60, cooldown: 0.7 },
      special: { id: 'phantomStrike', name: 'Phantom Strike', cooldown: 5, dmg: 55, dashLen: 12 },
      ult: { id: 'serpentStorm', name: 'SERPENT STORM', dmg: 24, hits: 8 },
    },
  },
  {
    id: 'nova', name: 'NOVA', title: 'The Starborn Oracle', icon: '✨', seed: 55,
    blurb: 'Built around a fragment of a collapsed star. Speaks in riddles, fights in constellations. Gravity is more of a suggestion to her.',
    quotes: { win: '"The stars foretold this. They usually do."', intro: '"Come — witness the light between worlds."' },
    colors: { primary: 0xd2d8e2, accent: 0x3fc8c8, glow: 0xff5ce8, stripes: false },
    body: { scale: 1.05, torsoW: 0.9, torsoH: 1.05, headSize: 0.85, armLen: 1.0, legLen: 1.08, hipW: 0.88, bulk: 0.85 },
    stats: { hp: 850, speed: 10, jump: 14, weight: 0.4, armor: 0.05 },
    ui: { power: 8, speed: 6, defense: 3 },
    moves: {
      light: { dmg: [28, 30, 42], knock: [4, 4, 10], range: 3.4 },
      heavy: { dmg: 72, knock: 17, range: 3.8, launch: 8 },
      ranged: { name: 'Plasma Lance', type: 'plasma', dmg: 55, speed: 28, cooldown: 1.3, splash: 3 },
      special: { id: 'starfall', name: 'Starfall Trio', cooldown: 7, dmg: 38, count: 3 },
      ult: { id: 'supernova', name: 'SUPERNOVA', dmg: 190, radius: 14 },
    },
  },
  {
    id: 'rhino', name: 'RHINO', title: 'The Unstoppable Object', icon: '🐂', seed: 66,
    blurb: 'One horn. One direction. Zero brakes. RHINO once charged through four buildings to win an argument he was already winning.',
    quotes: { win: '"HRRNGH! Next time — bring a wall that works!"', intro: '"You look like something worth flattening."' },
    colors: { primary: 0x76797f, accent: 0x9c2f2f, glow: 0xff4030, stripes: false },
    body: { scale: 1.22, torsoW: 1.2, torsoH: 1.0, headSize: 0.95, armLen: 1.08, legLen: 0.98, hipW: 1.12, bulk: 1.1 },
    stats: { hp: 1150, speed: 8.2, jump: 12, weight: 0.9, armor: 0.18 },
    ui: { power: 9, speed: 4, defense: 7 },
    moves: {
      light: { dmg: [40, 44, 60], knock: [6, 6, 14], range: 3.4 },
      heavy: { dmg: 95, knock: 24, range: 3.8, launch: 9 },
      ranged: { name: 'Shoulder Cannon', type: 'shell', dmg: 48, speed: 42, cooldown: 1.3, splash: 3 },
      special: { id: 'bullRush', name: 'Bull Rush', cooldown: 6.5, dmg: 75, knock: 26, dashLen: 16 },
      ult: { id: 'stampede', name: 'STAMPEDE', dmg: 60, hits: 3, knock: 30 },
    },
  },
  {
    id: 'tempest', name: 'TEMPEST', title: 'The Voltage Virtuoso', icon: '⚡', seed: 77,
    blurb: 'A weather-control unit that discovered showmanship. Every battle is a concert, every lightning bolt a chord. The crowd goes wild; the crowd is usually on fire.',
    quotes: { win: '"⚡ ENCORE? No? Suit yourselves. I was ELECTRIC."', intro: '"Lights up! The show starts NOW."' },
    colors: { primary: 0x2b3a6e, accent: 0x27b7d6, glow: 0x53e8ff, stripes: false },
    body: { scale: 1.06, torsoW: 0.95, torsoH: 1.0, headSize: 0.85, armLen: 1.02, legLen: 1.08, hipW: 0.9, bulk: 0.9 },
    stats: { hp: 880, speed: 11.5, jump: 15, weight: 0.42, armor: 0.04 },
    ui: { power: 7, speed: 8, defense: 3 },
    moves: {
      light: { dmg: [28, 30, 44], knock: [4, 4, 10], range: 3.2 },
      heavy: { dmg: 74, knock: 17, range: 3.6, launch: 8 },
      ranged: { name: 'Arc Bolt', type: 'lightning', dmg: 40, cooldown: 0.9, chainRange: 8 },
      special: { id: 'staticField', name: 'Static Overload', cooldown: 7, dmg: 70, radius: 8 },
      ult: { id: 'thunderfall', name: 'THUNDERFALL', dmg: 55, strikes: 8, radius: 12 },
    },
  },
  {
    id: 'fenrir', name: 'FENRIR', title: 'The Last Wild Thing', icon: '🐺', seed: 88,
    blurb: 'An autonomous hunter-frame that slipped its leash decades ago. Runs with no pack, answers to no handler, howls at every full moon — and every explosion.',
    quotes: { win: '"*low growl* ...The hunt was short. Run faster next time."', intro: '"I smell fear-coolant. It\'s yours."' },
    colors: { primary: 0x9aa3ad, accent: 0x3c444e, glow: 0x6cd8ff, stripes: false },
    body: { scale: 1.05, torsoW: 1.0, torsoH: 0.95, headSize: 0.9, armLen: 1.08, legLen: 1.1, hipW: 0.9, bulk: 0.92 },
    restPose: { thighL: [-31, 0, 0], thighR: [-31, 0, 0], kneeL: [57, 0, 0], kneeR: [57, 0, 0], ankleL: [-26, 0, 0], ankleR: [-26, 0, 0] },
    stats: { hp: 900, speed: 12.5, jump: 15, weight: 0.45, armor: 0.05 },
    ui: { power: 7, speed: 9, defense: 3 },
    moves: {
      light: { dmg: [30, 32, 46], knock: [4, 5, 11], range: 3.3 },
      heavy: { dmg: 76, knock: 18, range: 3.7, launch: 8 },
      ranged: { name: 'Rend Wave', type: 'wave', dmg: 36, speed: 34, cooldown: 1.0 },
      special: { id: 'pounce', name: 'Lunar Pounce', cooldown: 5.5, dmg: 65, leap: 14 },
      ult: { id: 'wildHunt', name: 'WILD HUNT', duration: 6, speedBoost: 1.5, dmgBoost: 1.6 },
    },
  },
  {
    id: 'colossus', name: 'COLOSSUS', title: 'The Patient Thunder', icon: '💣', seed: 99,
    blurb: 'A firebase that learned to walk, then learned chess. Plays the long game: every shell placed three moves ahead of where you plan to be.',
    quotes: { win: '"Checkmate was eight shells ago. You just heard it now."', intro: '"Range confirmed. This will be educational."' },
    colors: { primary: 0xb59a6a, accent: 0x6e6250, glow: 0xffd23c, stripes: true },
    body: { scale: 1.3, torsoW: 1.3, torsoH: 1.0, headSize: 0.85, armLen: 1.05, legLen: 0.95, hipW: 1.2, bulk: 1.15 },
    stats: { hp: 1300, speed: 6.5, jump: 11, weight: 1.0, armor: 0.24 },
    ui: { power: 9, speed: 2, defense: 9 },
    moves: {
      light: { dmg: [42, 46, 62], knock: [6, 6, 14], range: 3.5 },
      heavy: { dmg: 100, knock: 24, range: 3.9, launch: 9 },
      ranged: { name: 'Mortar Lob', type: 'mortar', dmg: 60, speed: 30, cooldown: 1.7, splash: 5.5 },
      special: { id: 'barrage', name: 'Fire Mission', cooldown: 8, dmg: 45, count: 5, radius: 9 },
      ult: { id: 'bigBertha', name: 'BIG BERTHA', dmg: 240, radius: 15 },
    },
  },
  {
    id: 'wraith', name: 'WRAITH', title: 'The Hollow Echo', icon: '🎯', seed: 110,
    blurb: 'Officially, this unit was scrapped years ago. Officially, nobody is picking off mechs from 800 meters. Officially, you are perfectly safe.',
    quotes: { win: '"...you were dead before the round began."', intro: '"*static* ...target acquired."' },
    colors: { primary: 0x2e3138, accent: 0x191b20, glow: 0xff3838, stripes: false },
    body: { scale: 1.02, torsoW: 0.85, torsoH: 1.0, headSize: 0.9, armLen: 1.05, legLen: 1.1, hipW: 0.85, bulk: 0.82 },
    restPose: { thighL: [-26, 0, 0], thighR: [-26, 0, 0], kneeL: [49, 0, 0], kneeR: [49, 0, 0], ankleL: [-23, 0, 0], ankleR: [-23, 0, 0] },
    stats: { hp: 800, speed: 11, jump: 14, weight: 0.35, armor: 0 },
    ui: { power: 8, speed: 7, defense: 2 },
    moves: {
      light: { dmg: [26, 28, 40], knock: [3, 4, 9], range: 3.0 },
      heavy: { dmg: 68, knock: 15, range: 3.4, launch: 7 },
      ranged: { name: 'Longshot', type: 'railgun', dmg: 85, cooldown: 1.9 },
      special: { id: 'cloak', name: 'Ghost Protocol', cooldown: 9, duration: 4, speedBoost: 1.3 },
      ult: { id: 'deadeye', name: 'DEADEYE', dmg: 110, shots: 3 },
    },
  },
  {
    id: 'inferno', name: 'INFERNO', title: 'The Joyful Furnace', icon: '🔥', seed: 121,
    blurb: 'A demolition unit whose safety governor "fell off" — twice. Finds fire genuinely hilarious. The laughter you hear over the flames? That\'s him having the best day ever.',
    quotes: { win: '"AHAHA! TOASTY! Anyone else cold? ANYONE?"', intro: '"Who ordered the flame-grilled special?!"' },
    colors: { primary: 0xb8321e, accent: 0x8c1d12, glow: 0xff8c1e, stripes: true },
    body: { scale: 1.18, torsoW: 1.18, torsoH: 1.0, headSize: 0.9, armLen: 1.05, legLen: 0.98, hipW: 1.08, bulk: 1.05 },
    stats: { hp: 1050, speed: 8.8, jump: 12.5, weight: 0.75, armor: 0.14 },
    ui: { power: 8, speed: 4, defense: 6 },
    moves: {
      light: { dmg: [36, 38, 54], knock: [5, 5, 12], range: 3.3 },
      heavy: { dmg: 86, knock: 20, range: 3.7, launch: 8 },
      ranged: { name: 'Dragon\'s Breath', type: 'flame', dmg: 8, cooldown: 0.09, range: 12 },
      special: { id: 'napalm', name: 'Napalm Carpet', cooldown: 7.5, dmg: 14, patches: 5, duration: 5 },
      ult: { id: 'backdraft', name: 'BACKDRAFT', dmg: 170, radius: 12, burnDmg: 10 },
    },
  },
  {
    id: 'glacier', name: 'GLACIER', title: 'The Cold Shoulder', icon: '❄️', seed: 132,
    blurb: 'Guardian of a polar research station, promoted to war machine by boredom. Devastating in combat, insufferable at parties — every joke is about ice, and he thinks they all land.',
    quotes: { win: '"Ice to beat you. ...I\'m contractually obligated to say that."', intro: '"Chill out. No? Fine — I\'ll handle it."' },
    colors: { primary: 0xbfd8e6, accent: 0x6fa8c8, glow: 0x9be8ff, stripes: false },
    body: { scale: 1.24, torsoW: 1.22, torsoH: 1.0, headSize: 0.9, armLen: 1.08, legLen: 0.98, hipW: 1.1, bulk: 1.08 },
    stats: { hp: 1200, speed: 7.5, jump: 12, weight: 0.92, armor: 0.2 },
    ui: { power: 8, speed: 3, defense: 8 },
    moves: {
      light: { dmg: [38, 42, 58], knock: [5, 6, 13], range: 3.4 },
      heavy: { dmg: 92, knock: 22, range: 3.8, launch: 9 },
      ranged: { name: 'Shard Burst', type: 'shard', dmg: 34, speed: 46, cooldown: 0.8 },
      special: { id: 'freezeBeam', name: 'Cryo Beam', cooldown: 8, dmg: 12, duration: 1.8, slow: 0.45 },
      ult: { id: 'absoluteZero', name: 'ABSOLUTE ZERO', dmg: 150, radius: 13, freezeTime: 2.5 },
    },
  },
];

export const ROSTER_BY_ID = Object.fromEntries(ROSTER.map((m) => [m.id, m]));
